repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0  
    hooks:
      - id: mypy
        additional_dependencies: [djangorestframework-simplejwt, django-simple-history, django-stubs, psycopg2-binary, python-dotenv, types-requests]  
        exclude: '^.*\/migrations\/.*$|^.*\/site-packages\/django-stubs\/.*$'
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.5 
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        args: ["--config=pyproject.toml"]
        language: system
        types: [python] 